parameters:
    dropbox.access_token: '%env(default::DROPBOX_ACCESS_TOKEN)%'
    salesforce.client_id: '%env(default::SALESFORCE_CLIENT_ID)%'
    salesforce.client_secret: '%env(default::SALESFORCE_CLIENT_SECRET)%'
    salesforce.username: '%env(default::SALESFORCE_USERNAME)%'
    salesforce.password: '%env(default::SALESFORCE_PASSWORD)%'
    salesforce.security_token: '%env(default::SALESFORCE_SECURITY_TOKEN)%'
    salesforce.login_url: '%env(default::SALESFORCE_LOGIN_URL)%'
    dropbox.app_key: '%env(default::DROPBOX_APP_KEY)%'
    dropbox.app_secret: '%env(default::DROPBOX_APP_SECRET)%'
    dropbox.refresh_token: '%env(default::DROPBOX_REFRESH_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        
        bind:
            Symfony\Component\RateLimiter\RateLimiterFactory $loginLimiter: '@limiter.login_limiter'
            Symfony\Component\RateLimiter\RateLimiterFactory $apiLimiter: '@limiter.api_limiter'
            Symfony\Component\RateLimiter\RateLimiterFactory $positionCreateLimiter: '@limiter.position_create_limiter'
            Symfony\Component\RateLimiter\RateLimiterFactory $supportCreateLimiter: '@limiter.support_create_limiter'

    App\:
        resource: '../src/'