framework:
    rate_limiter:
        login_limiter:
            policy: 'sliding_window'
            limit: 5
            interval: '1 minute'
        api_limiter:
            policy: 'sliding_window'
            limit: 60
            interval: '1 minute'
        position_create_limiter:
            policy: 'sliding_window'
            limit: 2
            interval: '1 minute'