<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260917041922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA9A621FA76ED395 ON user_attribute (user_id)');
        $this->addSql('CREATE INDEX IDX_FA9A621FB6E62EFA ON user_attribute (attribute_id)');
        $this->addSql('ALTER TABLE user_attribute ADD CONSTRAINT FK_FA9A621FA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_attribute ADD CONSTRAINT FK_FA9A621FB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_attribute DROP CONSTRAINT FK_FA9A621FA76ED395');
        $this->addSql('ALTER TABLE user_attribute DROP CONSTRAINT FK_FA9A621FB6E62EFA');
        $this->addSql('DROP TABLE user_attribute');
    }
}
