<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260920103707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE position_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE position_entity_attributes (position_entity_id INT NOT NULL, attributes_id INT NOT NULL, PRIMARY KEY (position_entity_id, attributes_id))');
        $this->addSql('CREATE INDEX IDX_AE1495FBD4047C20 ON position_entity_attributes (position_entity_id)');
        $this->addSql('CREATE INDEX IDX_AE1495FBBAAF4009 ON position_entity_attributes (attributes_id)');
        $this->addSql('ALTER TABLE position_entity_attributes ADD CONSTRAINT FK_AE1495FBD4047C20 FOREIGN KEY (position_entity_id) REFERENCES position_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE position_entity_attributes ADD CONSTRAINT FK_AE1495FBBAAF4009 FOREIGN KEY (attributes_id) REFERENCES attributes (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE position_entity_attributes DROP CONSTRAINT FK_AE1495FBD4047C20');
        $this->addSql('ALTER TABLE position_entity_attributes DROP CONSTRAINT FK_AE1495FBBAAF4009');
        $this->addSql('DROP TABLE position_entity');
        $this->addSql('DROP TABLE position_entity_attributes');
    }
}
