<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260923161352 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version INT DEFAULT 1 NOT NULL, user_id INT NOT NULL, me_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0FA76ED395 ON profile (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8157AA0F32785FF2 ON profile (me_id)');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0FA76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile ADD CONSTRAINT FK_8157AA0F32785FF2 FOREIGN KEY (me_id) REFERENCES user_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_entity ADD version INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE user_attribute ADD profile_id INT NOT NULL');
        $this->addSql('ALTER TABLE user_attribute ADD CONSTRAINT FK_FA9A621FCCFA12B8 FOREIGN KEY (profile_id) REFERENCES profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FA9A621FCCFA12B8 ON user_attribute (profile_id)');
        $this->addSql('ALTER TABLE user_profile DROP version');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0FA76ED395');
        $this->addSql('ALTER TABLE profile DROP CONSTRAINT FK_8157AA0F32785FF2');
        $this->addSql('DROP TABLE profile');
        $this->addSql('ALTER TABLE position_entity DROP version');
        $this->addSql('ALTER TABLE user_attribute DROP CONSTRAINT FK_FA9A621FCCFA12B8');
        $this->addSql('DROP INDEX IDX_FA9A621FCCFA12B8');
        $this->addSql('ALTER TABLE user_attribute DROP profile_id');
        $this->addSql('ALTER TABLE user_profile ADD version INT DEFAULT 1 NOT NULL');
    }
}
